# -*- coding: utf-8 -*-
"""Expense-tracker-categories-v4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J-ddBDimVVTbfen_lMQbZTE3Jv42ESrd
"""

# expense_tracker_v4.py

import csv
from datetime import datetime

# List to store expenses (instead of dict, so we can allow multiple items with same name)
expenses = []

print("Welcome to Expense Tracker with Categories + Date!")
print("Enter your expenses. Type 'q' when done.\n")

while True:
    item = input("Enter expense item (or 'q' to quit): ")
    if item.lower() == 'q':
        break

    category = input(f"Enter category for {item} (e.g., Food, Transport, Utilities): ")

    try:
        amount = float(input(f"Enter amount for {item}: "))
        date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")  # current date & time
        expenses.append([item, category, amount, date])
    except ValueError:
        print("❌ Invalid amount. Please enter a number.")

# Calculate total expenses
total = sum(exp[2] for exp in expenses)

# Show expenses
print("\n📝 Your Expenses:")
for exp in expenses:
    print(f"- {exp[0]} ({exp[1]}) : {exp[2]} on {exp[3]}")

print(f"\n💰 Total Expenses = {total}")

# Save to CSV
with open("expenses_v4.csv", mode="w", newline="") as file:
    writer = csv.writer(file)
    writer.writerow(["Item", "Category", "Amount", "Date"])
    for exp in expenses:
        writer.writerow(exp)
    writer.writerow(["Total", "", total, ""])

print("\n✅ Expenses saved to 'expenses_v4.csv'")