# -*- coding: utf-8 -*-
"""Untitled51.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1seKYjI5CHRU4JQfbUUR_nvrU19WdOlGy
"""

expenses = {"Food": 3000, "Transport": 1500, "Data": 2000}
total = sum(expenses.values())
print("Total Expenses:", total)

def add(x, y): return x + y
def subtract(x, y): return x - y
def multiply(x, y): return x * y
def divide(x, y): return x / y if y != 0 else "Error: Division by zero"

print("Calculator Example:")
print("10 + 5 =", add(10, 5))
print("10 - 5 =", subtract(10, 5))
print("10 * 5 =", multiply(10, 5))
print("10 / 5 =", divide(10, 5))

import random
import string

def generate_password(length=12):
    characters = string.ascii_letters + string.digits + string.punctuation
    password = ''.join(random.choice(characters) for i in range(length))
    return password

print("Generated Password:", generate_password(12))

weather = "rainy"  # pretend this is fetched from an API

if weather == "rainy":
    print("Don't forget your umbrella!")
elif weather == "sunny":
    print("Wear sunscreen today!")
else:
    print("Have a great day!")